rspatial/terra

src/RcppModule.cpp
src/crs.cpp

Found a couple of typos while trying to build.

Typos preventing build

---

R/rast.R
tests/testthat/test-matrix-input.R

*  remove stray code
* fix crs input
* +tests
These now work: 
```R
rast(volcano)
rast(cbind(as.matrix(expand.grid(1:3, 1:4)), 1:12)
```
(congrats)

matrix-input

---

.github/workflows/pkgdown.yml

`terra` couldn't be installed due to this error: 
```
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
```
I added a `gdal` install step to workflow and it now works.

fix pkgdown action

---

R/focal.R

- Have focal and focalCpp use first window instead of 1:prod(w)

edit focal test

---

man/ext.Rd

Simple update to documentation

Add link to other documentation for ext

---

R/lapp.R

Fix typo in lapp.R

---

man/crop.Rd

Edited typho

---

man/terra-package.Rd

Maybe there is a mistake here.

correct a doc mistake

---

man/setValues.Rd

Maybe my English is failing me, but to me this seems like a typo.

fix typo in setValues.Rd

---

src/spatFactor.cpp

Closes #1011; same root cause as #679

Include <iterator> for std::back_inserter

---

src/write_ogr.cpp

See https://clang.llvm.org/extra/clang-tidy/checks/readability/string-compare.html

use string equality operator over .compare()

---

src/geos_spat.h

See https://clang.llvm.org/extra/clang-tidy/checks/misc/definitions-in-headers.html

inline functions defined in header

---

DESCRIPTION

As introduced here:
https://github.com/rspatial/terra/blob/0298fa22a4f3e8b055dbe894f4c6cf691ed0d2a7/R/plot_let.R#L443

Add missing htmlwidgets to Suggests

---

R/time.R

Add time and timeInfo methods for SpatRasterDataset

time and timeInfo for SpatRasterDataset

---

src/ram.cpp

This fixes `terra` for macOS 32-bit. Tested on PowerPC.

Unbreak 32-bit macOS: powerpc/i386

---

R/focal.R

This just removes the error flag and then it seems to work as I would expect. See #1218

Allow fun mean with na.rm = TRUE and weights not is 0, 1, NA

---

R/focal.R
R/values.R
inst/tinytest/test_equal.R

error with na.policy = "omit" and multilayer SpatRaster bc it was reading all layer values in the checkNA step

fix bug related to #1218

---

.github/workflows/pkgdown.yml
.github/workflows/rcmdcheck.yml
R/Aclasses.R
man/plot.Rd

1. Update actions to newer versions
2. Run `rcmdcheck` on Windows and macOS too

update CI workflows

---

R/extract.R
R/extract_single.R
inst/tinytest/test_extract.R
man/extract.Rd

add 'raw = TRUE/FALSE' for extract method `SpatRaster,numeric`
allows raw matrix output of values for extract by cell

raw opt for extract(rast, cell)

---

.Rbuildignore
.gitignore
README.md
_pkgdown.yml
man/NAflag.Rd
man/terra-package.Rd

Maybe you will be interested, if not we can close. This PR:
1. Add a search bar.
2. Add "Description" and "Tutorials" tabs to the main bar.
3. Move the logo to the H1 header (otherwise it will be duplicated on the web page).

customise `pkgdown`

---

src/Makevars.ucrt

Revert "Use pkg-config on Windows when available."

---

man/is.valid.Rd

...pointing to related functions in ?topology

add "See also" section

---

man/project.Rd

...specifying that 'x' can now also be a SpatExtent or a matrix

add other object types allowed as 'x' argument

---

man/legend.Rd

Fix typo in legend.Rd

---

man/prcomp.Rd
man/princomp.Rd

- Should say see princomp if you want to use all values
- Change authors in prcomp since this is not based on the princomp implementation from RStoolbox
- Compare and contrast the two implementations
- Note maxcell argument
- Note that prcomp uses N-1

Update prcomp and princomp docs

---

man/terra-package.Rd

correct terra-package.Rd

---

R/spatvec.R
inst/tinytest/test_vect-geom.R
man/geometry.Rd
src/RcppModule.cpp
src/geos_methods.cpp
src/spatVector.h

Implements wish of #1609 
- geom() gains argument `wkb=FALSE`, if TRUE returns list of raw wkb vectors
- includes doc and test

wkb output option for geom() 

---

README.md

It looks like the tag associated with `terra` is pretty popular on StackOverflow. Maybe you would like to add the badge to the README? If not, close this PR.

add StackOverflow badge to README

---

man/vect.Rd

Description: mention more allowed file types other than Shapefile
See Also section: mention vector_layers()

vect.Rd: extend Description and See Also

---

man/width.Rd

Please feel free to ignore, but to me this makes it much easier to understand what the function does.

width.Rd: add plot to Examples

---

man/sds.Rd

I propose this change to make the description of `sds()` a little clearer.

improve `sds.Rd`

---

R/plot.R
man/text.Rd

addressing issue #1712 . Feel free to ignore, in which case I'll just use it privately :)

add 'jitter' argument to text()
