- .Rbuildignore
- .gitignore
- README.md
The new geos functions requires libgeos++-dev on linux to get the correct header files. Also added a few lines to the gitignore and Rbuildignore that make life easier when using Rstudio to build.
> New dependency on Linux

- README.md
A slightly less concise alternative would be:
```
`terra` is a replacement of the [raster](https://github.com/rspatial/raster) R package.
```
> Fix README typo, improve clarity, use fewer words

- README.md
Links to the {terra} tutorial are not correct the first time on https://rspatial.org/terra/.  I think using https://rspatial.org/terra/index.html will better work.
> Add index.html as redirection is not perfect

- src/Makevars.win
Stay in sync with rgdal, sf, and others.
> Windows: update to GDAL 3.2.1 stack

- .github/workflows/pkgdown.yml
Website building by `pkgdown` workflow hasn't been working for several days (https://github.com/rspatial/terra/actions/workflows/pkgdown.yml). The error occur when installing GDAL and is related to linking to GFortran. The proposed solution is to remove GFortran, so I did. After that, `pkgdown` works fine. 
```
==> Installing gdal dependency: gcc
==> Pouring gcc--11.1.0.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gfortran
Target /usr/local/bin/gfortran
already exists. You may want to remove it:
rm '/usr/local/bin/gfortran'
To force the link and overwrite all conflicting files:
brew link --overwrite gcc
To list all files that would be deleted:
brew link --overwrite --dry-run …
```
> remove GFortran before installing GDAL in pkgdown

- .github/workflows/pkgdown.yml
`pkgdown` workflow [fails](https://github.com/rspatial/terra/actions/workflows/pkgdown.yml) in some cases due to the below error. Explicitly specifying `proj` for installation should fix this problem. 
```
checking proj.h usability... no
checking proj.h presence... no
checking for proj.h... no
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘terra’
```
> Install proj in pkgdown workflow

- README.md
This is just a minor change to link directly to [terra] tagged questions on StackOverflow so that users are aware of what have been asked.
> Link directly to [terra] tagged questions on StackOverflow

- src/read_gdal.cpp
When processing many files in a loop, this leak eventually causes R to crash because too many files are open. Using managed pointers (`std::unique_ptr`, `std::shared_ptr`) with a custom deleter would also avoid this.
> Avoid dangling GDAL dataset

- R/relate.R
I believe this fixes issue #328 . `to_int <- as.data.frame(intersect(to, y))` results in a data frame that is out of order with respect to the input data frame `to`, causing incorrect `to_id` in the output of `nearest()`. I suspect there may be a better approach here, mostly submitting this PR to point to where the issue is occurring.
> fix incorrect to_id in nearest()

- R/generics.R
- man/project.Rd
Made a very minor change to `terra::project()`, to change the default `method` depending on whether `x` is categorical (`method = "near"`) or continuous (`method = "bilinear"`). I think this is a more sensible default, because I've never personally not wanted to preserve levels when projecting a categorical raster (others may have different experiences?). The changed function still allows the user to override this behaviour if they want to of course.
Updated the docs for `project` accordingly, and also fixed a typo in there too.
Cheers! -Matt
> Change to terra::project, so the default method is "near" if x is categorical

- NAMESPACE
- R/RcppExports.R
- src/RcppExports.cpp
- src/RcppFunctions.cpp
This PR adds functions to check and set the GDAL cache size. I'm not sure if it's a good idea to expose low-level functionality like this in terra, and I'm curious what you think.
My motivation for doing so is to detect situations where `exactextractr` will perform poorly. I am working with a netCDF dataset that uses a very large chunk size. If I simultaneously extract from 1000 bands of the dataset it takes a few seconds, but increasing this to 1100 bands increases the runtime to 10-15 minutes. The reason is that the last 100 bands push us over the limit of GDAL's block cache, so every band is decompressed with for every feature that I'm extracting. Since I can anticipate memory requirements before the operation, I could throw a warning and direct the user to increase the cache size or …
> Add functions to check and set GDAL cache size

- configure
- configure.ac
Similar to the sf package (see similar PR: https://github.com/r-spatial/sf/pull/1835), this adds an `--with-sqlite3-lib` configure argument to specify a non-standard location for sqlite3 libraries. As far as I understand this is only needed for the linking test during installation.
I'm not sure why runstatedir was removed from configure, so feel free to fix it directly or let me know how I can fix it. I generated configure with autoconf/2.69.
> Add --with-sqlite3-lib configure arg

- man/project.Rd
For project(), x can also be a SpatRaster, but the current documentation only says "SpatVector".
> x can be a SpatRaster

- inst/tinytest/test_matrix-input.R
tests for the defaults established in #1 
(I think they run ok, I'm new to tinytest)
just for the record, there were some tests but they were removed in the move to tinytest: https://github.com/rspatial/terra/pull/22/commits/65fe6eafcf62f65b074eea5df712c3ca57de743a
so, a todo (for me) might be to scan the old testthat tests for coverage)
> tests for array/matrix input extent

- inst/tinytest/test_extent.R
The behavior here changed recently, so I thought it would be good to add a test to pin it down.
> Add test for SpatExtent intersection

- man/writeRaster.Rd
> typo: man page for writeRaster.Rd was missing \ in \link

- src/Makevars.win
Wrap-up GDAL update for R 3.3.0 - 4.1.3 on Windows. Also adds support for zstd tiff files. This update does not affect the new R-4.2 ucrt builds which you have hardcoded separately in [src/Makevars.ucrt](src/Makevars.ucrt).
Also fixes #473
> Windows: update libs for R < 4.2

- R/xyRowColCell.R
- man/xyCellFrom.Rd
PR to add defaults for `row`, `col` args in `xFromCol`, `yFromRow`, see #583
> default row/col for xFromCol,yFromRow if missing

- R/levels.R
- R/show.R
- inst/tinytest/test_cats.R
This PR fixes `active_cats()`and `show(<SpatRaster>)` to achieve the expected behavior from my issue #563:
``` r
library(terra)
#> terra 1.5.23
x <- rast(lapply(1:3, \(i) set.crs(rast(matrix(round(runif(33 ^ 2, 0, 2)), 33, 33)), "EPSG:4326")))
set.seed(123)
spatSample(x, 3)
#>   lyr.1 lyr.1.1 lyr.1.2
#> 1     2       1       1
#> 2     2       1       2
#> 3     0       1       2
levels(x) <- LETTERS[1:3]
set.seed(123)
spatSample(x, 3)
#>   lyr.1 lyr.1.1 lyr.1.2
#> 1     C       1       1
#> 2     C       1       2
#> 3     A       1       2
levels(x) <- rep(list(LETTERS[1:3]), 3)
set.seed(123)
spatSample(x, 3)
#>   lyr.1 lyr.1.1 lyr.1.2
#> 1     C       B       B
#> 2     C       B       C
#> 3     A       B       C
show(x)
#> class       : SpatRaster 
#> dimensions  : 33, 33, 3  (nrow, …
```
> Fix handling of categories in SpatRaster with multiple layers

- src/write_gdal.cpp
Hi Robert
It would be great to have a more verbose message for insufficient space. Now the error message would look like:
> Error: [merge] insufficient disk space. Need: 71 GB. Available: 41 GB.
I have very little knowledge of cpp, so please check carefully. In particular, I am not sure about the digits printed out by `std::to_string`? Here it seems there is some rounding occurring? So I am not sure how the output looks like when the disk <1GB, though this seems a very unexpected case.
> More informative error message for insufficient disk: indicate required and available space

- src/read_gdal.cpp
- uses newer `describe(sds=TRUE)` syntax in message from `SpatRaster::constructFromSDS`
> Update SpatRaster "skipped sub-datasets" message 

- inst/tinytest/test_extract.R
- src/extract.cpp
Hey guys,
I've picked up an error in the handling of NaNs in the bilinearInt method for the extract method. 
See the example below:
```
r <- terra::rast(nrow = 2, ncol = 2, nlyrs = 1, xmin = -100, xmax = 100, ymin = -100, ymax = 100)
terra::values(r) <- c(100, 100, NaN, 100)
print(terra::extract(r, data.frame(X = 45.0, Y = 45.0), method = "bilinear")$lyr.1)
```
Here the expected bilinear interpolation between points all with value 100 should always stay at 100 but we dip down to 55, 145. A quick peek at the source code shows that the handling isn't linearly adjusting when a NaN is found and simply using the value 0.5 which can lead to problems say when (y - y2) happens to be very small or very large; see below
https://github.com/rspatial/terra/blob/1820db49ed7173bb94656b38f2614dfb640f2f10/ …
> fix for bilinearInt NaN handling

- man/extract.Rd
In fact, are matrix ever returned by `extract`? If not, the Value field should also be updated to reflect that it only returns a `list` or a `data.frame`.
> typo: when list = FALSE, extract returns a data.frame, not a matrix

- man/vrt.Rd
Improves documentation for #747.
I also wonder if the expansion of the VRT acronym as Virtual Raster Tiles is correct. The GDAL documentation uses Virtual Dataset (https://gdal.org/programs/gdalbuildvrt.html).
> improve `vrt()` doc

- R/pack.R
BTW: `paste0(tempfile(), ".tif")` can be `tempfile(fileext = ".tif")`.
> fix save path in `wrap()`

- .github/workflows/pkgdown.yml
- .github/workflows/rcmdcheck.yml
Sometimes pkgdown workflow fails on the pandoc installation so maybe updating this will help.
> update GHA workflows

- src/Makevars.ucrt
- src/Makevars.win
When building terra from source on my work (Windows) machine (which has Rtools42 installed in "C:/Program Files/rtools42/") I get the following error. 
```
cp -r C:/Program Files/rtools42/x86_64-w64-mingw32.static.posix/share/gdal ../inst/
cp: cannot stat 'C:/Program': No such file or directory
cp: cannot stat 'Files/rtools42/x86_64-w64-mingw32.static.posix/share/gdal': No such file or directory
make: *** [Makevars.ucrt:22: winlibs] Error 1
ERROR: compilation failed for package 'terra'
```
This appears to be because the path `$R_TOOLS_SOFT` has spaces in the name and is not quoted. Since this is my work computer I unfortunately have no control over where Rtools is installed. Adding quotes around the relevant path in Makevars.ucrt fixes the issue for me.
I assume this also could affect …
> Makevars updates for Windows

- .github/workflows/pkgdown.yml
It seems that linking to `gfortran` works better in the new version of macOS, so we don't have to unnecessarily remove and reinstall it.
> update pkgdown workflow

- man/extract.Rd
I think it is worth mentioning `zonal()` in the `extract()` documentation as an alternative way, because `zonal()` may be more efficient in some cases. Here is simple example:
```r
f = system.file("ex/lux.shp", package = "terra")
v = vect(f)
n = 2000
r = rast(v, nrows = n, ncols = n, names = "value")
values(r) = rnorm(ncell(r))
system.time({
x1 = extract(r, v, fun = "mean")
})
#> user  system elapsed
#> 8.34    0.47    8.84
system.time({
rr = rasterize(v, r, field = seq_len(nrow(v)))
x2 = zonal(r, rr, "mean")
})
#> user  system elapsed
#> 0.25    0.14    0.39
all.equal(x1$value, x2$value)
#> TRUE
```
> Mention `zonal()` in `extract()` docs

- R/geom.R
Fix the problem reported in #979
seems that it was just a typo.
> fix typo in split() #979

- R/sample.R
possible fix for #991
Feel free to improve on it or fix it otherwise tho :)
````
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
plot(r)
s <- spatSample(r, 100 , "regular", as.raster=TRUE)
plot(s)
s2 <- spatSample(r, round(c(nrow(r)/2,ncol(r)/2)), "regular", as.raster=TRUE)
plot(s2)
#####################
s <- spatSample(r, 1000000 , "regular", as.raster=TRUE)
plot(s)
s2 <- spatSample(r, round(c(nrow(r)+1,ncol(r)+1)), "regular", as.raster=TRUE)
plot(s2)
````
> fix sampling a raster with two dimension

- src/spatRaster.h
See https://clang.llvm.org/extra/clang-tidy/checks/readability/avoid-const-params-in-decls.html
> Remove no-op const qualification in header

- R/spatvec.R
Hello Robert!
Warning `Warning: [as.points] raster has no values` is issued by `crds()` when used on a template (no values) SpatRaster.
With current development terra 1.7-33:
``` r
library(terra)
#> terra 1.7.33
r <- rast(matrix(rep(NaN, 9), ncol=3))
crds(r, na.rm = FALSE) |> head(3)
#>        x   y
#> [1,] 0.5 2.5
#> [2,] 1.5 2.5
#> [3,] 2.5 2.5
crds(rast(r), na.rm = FALSE) |> head(3)
#> Warning: [as.points] raster has no values
#>        x   y
#> [1,] 0.5 2.5
#> [2,] 1.5 2.5
#> [3,] 2.5 2.5
as.points(rast(r), values = FALSE) |> crds() |> head(3)
#>        x   y
#> [1,] 0.5 2.5
#> [2,] 1.5 2.5
#> [3,] 2.5 2.5
all.equal(values(r), values(rast(r)))
#> Warning: [readValues] raster has no values
#> [1] TRUE
```
I think that it makes sense to warn about missing values when values are …
> `crds(<SpatRaster>)`: use `as.points(..., values=FALSE)` to avoid warnings

- R/generics.R
- src/RcppModule.cpp
- src/gdal_algs.cpp
- src/spatRaster.h
(rewritten PR to get past merge issue, previous were #1120 and #1216)
Propose to use *GDALWarp utility library* for  `project()` raster rather than with ChunkAndWarpImage. 
The benefit is automatic choice  of a reasonable overview for multi-zoom sources (like large GeoTIFFs or image tile servers), (and hence very fast read, with data resolution suitable for target raster even over large regions.  
**The problem remains that  we only access bands from the first source.**  see below
(This doesn't address the capability for collections, but I think it's worth sharing as is now because that will require a solution for the multiple sources, and maybe that can just be done at the R level). 
Currently is a lot slower in terra for online image servers and very large COGs because there's no …
> project raster via GDALWarp() app lib

- man/focal.Rd
I've included some changes that I think would clarify `w` for focal. Some changes to the documentation include:
- preferentially suggesting the use `NA` over 0 in `w` as this is safer since it masks those cells out of calculations rather than setting them to 0 which may affect calculations depending on the function.
- Describes what the weights do in calculations and removes restriction that they must be between 0 and 1.
- Slight edit to special case of mean stating that the weighted mean will be calculated rather than just saying 0's function like NA's.
> Improve clarity of documentation for focal weights

- R/SpatRasterDataset.R
- R/tiles.R
A small PR to restore compatibility with older versions of R < 4.1 by using the `function` keyword rather than the newer inline anonymous function syntax.
I looked quickly for other uses of `\()` in `R/` and think I got them, but may have been mislead by GitHub code search
> Use full `function` keyword in `tiles.R`

- R/names.R
`set.names()` wasn't working properly for `SpatRasterDataset` or `SpatRasterCollection` - here's a example testing `set.names` with the different `Spat*` classes:
```r
library(terra)
r <- c(rast(), rast())
set.names(r, c("a", "b"))
names(r)
#> [1] "a" "b"
r <- sds(rast(), rast())
set.names(r, c("a", "b"))
#> Warning in 1:nlyr(x): numerical expression has 2 elements: only the first used
#> Error in if (length(value) != nlyr(x)) {: the condition has length > 1
names(r)
#> [1] "" ""
r <- sprc(rast(), rast())
set.names(r, c("a", "b"))
#> Warning in 1:nlyr(x): numerical expression has 2 elements: only the first used
#> Error in if (length(value) != nlyr(x)) {: the condition has length > 1
names(r)
#> [1] "" ""
v <- vect(cbind(0,0), atts = data.frame(x = 1, y = 2))
set.names(v, c("a", "b")) …
```
> fix error in `set.names()`

- src/spatDataframe.h
**terra** fails to install on latest Alpine Linux 3.19.0:
```
In file included from spatVector.h:21,
from spatRaster.h:20,
from spatRasterMultiple.h:18,
from arith.cpp:19:
spatDataframe.h:51:41: error: 'int8_t' was not declared in this scope
51 |                 std::vector<std::vector<int8_t>> bv;
|                                         ^~~~~~
spatDataframe.h:28:1: note: 'int8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```
I can confirm that this patch fixes installation on Alpine Linux.
> fix compilation failure on latest Alpine 3.19.0

- man/layerCor.Rd
...which has 3 rather than 2 items, and NaN rather than NA
> update Value section with current output

- man/plet.Rd
The current CRAN version of `leafet` now supports `SpatVector` and `SpatRaster`, so the text in `plet` stating that the development version is needed is no longer necessary. I made sure this was the case with the following code (I have the CRAN version of `leaflet`): 
```r
library(terra)
v <- vect(system.file("ex/lux.shp", package = "terra"))
r <- rast(system.file("ex/elev.tif", package = "terra"))
plet(v)
plet(svc(v))
plet(r)
```
> update `plet()` documentation

- R/write.R
This PR makes it easier to write Seek-Optimized ZIP (SOZIP)-enabled Shapefile (.shz, .shp.zip extensions) and GeoPackage (.gpkg.zip extension) without manual specification of the `filetype` in `writeVector()`
This works with GDAL >= 3.7. 
``` r
library(terra)
#> terra 1.7.74
x <- vect(system.file('ex', 'lux.shp', package = "terra"))
writeVector(x, "test.shz")
file.size("test.shz")
#> [1] 33549
writeVector(x, "test.shp")
file.size("test.shp")
#> [1] 64692
writeVector(x, "test.shp.zip")
file.size("test.shp.zip")
#> [1] 33589
writeVector(x, "test.gpkg.zip")
file.size("test.gpkg.zip")
#> [1] 37926
writeVector(x, "test.gpkg")
file.size("test.gpkg")
#> [1] 172032
```
---
From https://gdal.org/user/virtual_file_systems.html#sozip-seek-optimized-zip
> [SOZip (Seek-Optimized …
> Autodetect drivers for SOZIP-enabled write of .shz, .shp.zip, .gpkg.zip files

- R/show.R
`osVersion` is documented to be `NULL` on some "bizarre systems" (including the one where we run our tests :) ).
On such systems, there will be widespread package issues because of issues resulting from assuming this `grepl()` will return `TRUE` or `FALSE` (instead of `logical()`).
> Robustly use osVersion

- configure
- configure.ac
See https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/terra-00check.html. First is unneeded, as R >=3.5.0 is required in DESCRIPTION. The second is needed, and the edit works, checked both with _R_CHECK_BASHISMS_=true _R_CHECK_BASHISMS_EXTRA_=true and R-devel, and against a doctored gdal-config reporting 3.6.0.
> fix bashisms

- src/read_gdal.cpp
- src/write_gdal.cpp
Following up on https://github.com/rspatial/terra/pull/1696#issuecomment-2581046017 I did some analysis on removing driver restrictions for reading and writing raster metadata. 
It seems that with removing a few conditional statements we can write either .aux.xml or internal metadata for time and units for many more drivers than just GTiff. 
I wrote a routine (see [this Gist](https://gist.github.com/brownag/db0b5d5c7d128896cff48bc95eb95b35)) to attempt to write and read a raster with metadata using all available raster drivers. The .aux.json is deleted prior to read, so any metadata that are read are those written using GDAL `SetMetadataItem()`, not the terra-specific .aux.json function.
The following is from testing with GDAL 3.10.0 and config option `GDAL_PAM_ENABLED=YES` (default). 
Of …
> Generalize raster metadata 

- R/plot.R
It's probably not necessary to break the code just because of a larger `n` than possible, e.g. when we do `plot(my_object, col = map.pal("random", nrow(my_object)))`. I'd just coerce `n` to the maximum possible value, with a message or warning.
> map.pal warning (not error) when random n>433

- R/Arith_generics.R
I'm not sure what the implications of this mistake (if any) are, but I happened to find this searching around for something else, so sending along the fix.
> typo: iSTRUE --> isTRUE

- R/geom.R
An error message for `hull()` states that "concave_polygons" is a valid option for `hull()` - however, this is not the case:
``` r
library(terra)
#> terra 1.8.26
v <- vect(system.file("ex/lux.shp", package = "terra"))
h <- hull(v, type = "abcd")
#> Error in match.arg(tolower(type), c("convex", "rectangle", "circle", "concave_ratio", : 'arg' should be one of "convex", "rectangle", "circle", "concave_ratio", "concave_length", "concave_polygons"
h <- hull(v, type = "concave_polygons")
#> Error: [hull] unknown hull type
```
<sup>Created on 2025-04-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
There's a mismatch between the R and C++ methods:
https://github.com/rspatial/terra/blob/85fa6ad6443f6713f83bbc98d681acc4faf25715/R/geom.R#L357 …
> Remove 'concave_polygons' from list of allowed hull types

- .github/workflows/rcmdcheck.yml
We found on r-universe that this package crashes on load on Windows 2025 (but not on Windows 2022).
```
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
ERROR: loading failed
* removing 'D:/a/terra/terra/check/terra.Rcheck/terra
```
I have no idea how to debug this with the current Rtools, perhaps @kalibera can help.
> Test on Win2025

- R/animate.R
I get much better effect with dev.hold to avoid flashing, .eg. (tested on Windows and via X over ssh)
```
s <- rast(system.file("ex/logo.tif", package="terra"))   
anim <- function(x, pause=0.25, main, range, maxcell=50000, n=1, ...) {
if (missing(main)) {
main <- names(x)
}
#x <- spatSample(x, size=maxcell, method="regular", as.raster=TRUE, warn=FALSE)
x <- terra:::sampleRaster(x, maxcell, method="regular", replace=FALSE, ext=NULL, warn=FALSE, overview=TRUE)
if (missing(range)) {
mnmx <- minmax(x)
range <- c(min(mnmx[1,]), max(mnmx[2,]))
}
nl <- nlyr(x)
n <- max(1, round(n))
i <- 1
reps <- 0
while (reps < n) {
plot(x[[i]], main = main[i], range=range, maxcell=Inf, ...)
grDevices::dev.flush()
grDevices::dev.hold()
Sys.sleep(pause)
i <- i + 1
if (i > nl) {
i <- 1
reps <- reps+1
}
}
} …
```
> dev.hold() for animate

- src/RcppFunctions.cpp
This fixes an out-of-bounds write when setting up proj search paths. It is the cause for crashes reported in https://github.com/rspatial/terra/issues/1813.
> Fix setting up proj search paths.

- R/extract.R
- inst/tinytest/test_extract.R
Since the fix for https://github.com/rspatial/terra/issues/1818, numerical layer indexing is broken in extract(), except when unique(layer) is equal to seq_len(max(layer)), as discussed in issue #1862
This PR fixes that by remapping the layer indices to match the new ordering induced by the `x <- x[[unique(layer)]]` transformation.
> Handle reordering of numerical layer index in extract(), see issue #1862

- man/aggregate.Rd
Hi, when using the aggregate function I feel a little confused about what happens when fact is a double value. I've added more detailed instructions and an example to help.
So I have adjusted the description of the **_fact_** parameter of the `aggregate` function and added an example for two values of **_fact_**.
If there are elements where I made mistakes, please forgive and feel free to change them.
> Adjust the description of the fact parameter of the `aggregate` function and add the example

- man/app.Rd
I've often found myself wanting to use global() but checking app() instead, and not remembering the name of global(). So, I think this mention would be useful for redirecting users.
> mention global() in SeeAlso

- R/animate.R
...rather than the minmax of all layers combined. Otherwise, the range is not appropriate for layers that vary within very different scales, e.g. WorldClim.
> animate: allow adapting range to each layer
